[background]
path = "/home/hannibal/dotfiles/wallpapers/rocket_launch.jpg"
fit = "Fill"

[commands]
reboot = [ "loginctl", "reboot" ]
poweroff = [ "loginctl", "poweroff" ]

[GTK]
application_prefer_dark_theme = true
theme_name = "Tokyonight-Dark-Storm"
